### PR TITLE
Fix Possible Memory Leak in `dasher`

### LINKED ISSUE #2923: Possible memory leak in long-running HLS live packaging
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

GPAC version: https://github.com/gpac/gpac/commit/e2250d68fd67cfa770b270b0ac882a39e4e93f32

There seems to be a memory leak when running GPAC, consuming from a TCP socket carrying TS and packaging into HLS CMAF. 

```
valgrind --leak-check=full --log-file=/home/juan/workspace/video-engineering/recordings/20240724_gpac_leak/valgrind.txt /home/juan/workspace/git/gpac/bin/gcc/gpac -i tcp://localhost:5020/:gpac:tsprobe=true:listen=false reframer:rt=on -o "/home/juan/workspace/video-engineering/recordings/20240724_gpac_leak/media/playlist.m3u8:gpac:buf=-150:ll_part_hb=-1:seg_sync=no:segdur=1.0:cdur=1.0:llhls=sf:hlsc=true:cmaf=cmf2:dmode=dynamic:pssh=mv:template=segment_normal_hls:hmode=push:max_cache_segs=16:keep_segs=false"
```

Running for 30 min or so, valgrind reports the memory leak below

## Valgrind report

```
==83621== Memcheck, a memory error detector
==83621== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==83621== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==83621== Command: /home/juan/workspace/git/gpac/bin/gcc/gpac -i tcp://localhost:5020/:gpac:tsprobe=true:listen=false reframer:rt=on -o /home/juan/workspace/video-engineering/recordings/20240724_gpac_leak/media/playlist.m3u8:gpac:buf=-150:ll_part_hb=-1:seg_sync=no:segdur=1.0:cdur=1.0:llhls=sf:hlsc=true:cmaf=cmf2:dmode=dynamic:pssh=mv:template=segment_normal_hls:hmode=push:max_cache_segs=16:keep_segs=false:inband_event
==83621== Parent PID: 9763
==83621== 
==83621== 
==83621== HEAP SUMMARY:
==83621==     in use at exit: 235,730 bytes in 4,685 blocks
==83621==   total heap usage: 995,220 allocs, 990,535 frees, 571,386,572 bytes allocated
==83621== 
==83621== 91,992 bytes in 3,713 blocks are definitely lost in loss record 275 of 275
==83621==    at 0x484DB80: realloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==83621==    by 0x492E2D3: gf_realloc (alloc.c:160)
==83621==    by 0x4EB2344: dasher_process_hls_ll (dasher.c:10073)
==83621==    by 0x4EB27A7: dasher_process_event (dasher.c:10153)
==83621==    by 0x4E3D42B: gf_filter_pid_send_event_downstream (filter_pid.c:7749)
==83621==    by 0x4E52991: gf_fs_thread_proc (filter_session.c:2171)
==83621==    by 0x4E53402: gf_fs_run (filter_session.c:2478)
==83621==    by 0x11604F: gpac_main (gpac.c:1598)
==83621==    by 0x116484: main (gpac.c:1854)
==83621== 
==83621== LEAK SUMMARY:
==83621==    definitely lost: 91,992 bytes in 3,713 blocks
==83621==    indirectly lost: 0 bytes in 0 blocks
==83621==      possibly lost: 0 bytes in 0 blocks
==83621==    still reachable: 141,722 bytes in 951 blocks
==83621==         suppressed: 0 bytes in 0 blocks
==83621== Reachable blocks (those to which a pointer was found) are not shown.
==83621== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==83621== 
==83621== For lists of detected and suppressed errors, rerun with: -s
==83621== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

### PR DESCRIPTION
**Pull request by DenizUgur**
fixes #2923

### CODE REVIEW

File: src/filters/dasher.c [hunk 1]
```diff
@@ -10070,11 +10070,13 @@ static void dasher_process_hls_ll(GF_DasherCtx *ctx, const GF_FilterEvent *evt)
 		GF_LOG(GF_LOG_ERROR, GF_LOG_DASH, ("[Dasher] Received segment size info event but no pending segments\n"));
 		return;
 	}
-	sctx->frags = gf_realloc(sctx->frags, sizeof (GF_DASH_FragmentContext) * (sctx->nb_frags+1));
-	if (!sctx->frags) {
+	void *new_frags = gf_realloc(sctx->frags, sizeof (GF_DASH_FragmentContext) * (sctx->nb_frags+1));
+	if (!new_frags) {
+		gf_free(sctx->frags);
```
Comment (aureliendavid) [inline src/filters/dasher.c:10075]: Hi, 

Looks good, just a small thing: when we free a pointer inside a structure, it's good practice to force-set it to null to avoid double-frees and such things later on.

Comment (DenizUgur) [reply src/filters/dasher.c:10075]: Thank you for the tip

**Comment by aureliendavid** [comment]
thanks for the fix!
